name: enjoy-slurm_docs
channels:
  - conda-forge
  - nodefaults
dependencies:
   - pandas
   - numpydoc
   - sphinx
   - ipython
   - nbconvert
   - nbformat
   - ipykernel
   - ipython_genutils
   - pandoc
   - jinja2<3.1
   - pip
   - sphinx-book-theme
   - pip:
     - docrep<=0.2.7
     - jupyter_client
     - nbsphinx
     - sphinx-copybutton
     - sphinxcontrib-srclinks
