name: enjoy-slurm_docs
channels:
  - conda-forge
  - nodefaults
dependencies:
   - pandas
   - numpydoc
   - sphinx
   - ipython
   - nbconvert
   - nbformat
   - ipykernel
   - ipython_genutils
   - pandoc
   - pip
   - sphinx-book-theme
   - nbsphinx-link
   - nbsphinx
   - jupyter_client
   - sphinx-copybutton
   - sphinxcontrib-srclinks
